import { Product } from "@/types/Product";

const products: Product[] = [
	{
		name: "organic farm fresh honey",
		slug: "organic-farm-fresh-honey",
		description:
			"Pure organic honey harvested from wildflower meadows. Rich golden color with natural floral notes. Perfect for sweetening tea, baking, or drizzling over yogurt. No additives or preservatives, just pure honey goodness. Sourced directly from local beekeepers who practice sustainable beekeeping. Contains natural enzymes and antioxidants.",
		featured: true,
		image: "/products/pexels-1092730.jpeg",
		price: 850,
		specialPricePercent: 15,
		isNew: true,
		clerkId: "clerk_organic_honey_001",
		categoryId: "beverages",
	},
	{
		name: "artisan sourdough bread",
		slug: "artisan-sourdough-bread",
		description:
			"Handcrafted sourdough bread made with premium flour and slow fermentation. Crispy crust with a tender, tangy interior. Prepared fresh daily using traditional baking methods. High in fiber and probiotic cultures. Perfect for sandwiches or enjoying with quality butter and cheese.",
		featured: true,
		image: "/products/pexels-5632399.jpeg",
		price: 450,
		specialPricePercent: 10,
		isNew: false,
		clerkId: "clerk_sourdough_bread_002",
		categoryId: "snacks",
	},
	{
		name: "cold-pressed olive oil",
		slug: "cold-pressed-olive-oil",
		description:
			"Extra virgin olive oil from Mediterranean vineyards, cold-pressed to preserve nutrients and flavor. Smooth fruity notes with subtle peppery finish. Rich in polyphenols and healthy monounsaturated fats. Ideal for salads, dipping, and finishing dishes. Harvest guaranteed within the season.",
		featured: true,
		image: "/products/pexels-1092730.jpeg",
		price: 1200,
		specialPricePercent: 12,
		isNew: false,
		clerkId: "clerk_olive_oil_003",
		categoryId: "italian",
	},
	{
		name: "grass-fed beef jerky",
		slug: "grass-fed-beef-jerky",
		description:
			"Premium beef jerky from 100% grass-fed cattle. Slow-dried using natural smoking techniques with hickory wood. No artificial preservatives, nitrates, or fillers. High protein snack perfect for on-the-go. Rich, savory flavor with a tender yet chewy texture. Packed with essential amino acids.",
		featured: false,
		image: "/products/pexels-5632396.jpeg",
		price: 1500,
		specialPricePercent: 20,
		isNew: false,
		clerkId: "clerk_beef_jerky_004",
		categoryId: "snacks",
	},
	{
		name: "organic sencha green tea",
		slug: "organic-sencha-green-tea",
		description:
			"Vibrant organic sencha with grassy aroma and a clean, sweet finish. Shade-grown leaves are steamed quickly to preserve color and nutrients. Great for daily sipping and rich in antioxidants.",
		featured: false,
		image: "/products/pexels-1417945.jpeg",
		price: 520,
		specialPricePercent: 10,
		isNew: false,
		clerkId: "clerk_green_tea_005",
		categoryId: "beverages",
	},
	{
		name: "single-origin coffee beans",
		slug: "single-origin-coffee-beans",
		description:
			"Medium roast coffee beans from high-altitude farms with notes of caramel and citrus. Freshly roasted in small batches for balanced sweetness and clean finish.",
		featured: true,
		image: "/products/pexels-894695.jpeg",
		price: 980,
		specialPricePercent: 15,
		isNew: true,
		clerkId: "clerk_coffee_beans_006",
		categoryId: "beverages",
	},
	{
		name: "70% dark chocolate bar",
		slug: "70-dark-chocolate-bar",
		description:
			"Rich 70% cacao dark chocolate with a smooth melt and subtle berry notes. Made with ethically sourced cacao and minimal ingredients.",
		featured: false,
		image: "/products/pexels-918327.jpeg",
		price: 300,
		specialPricePercent: 12,
		isNew: false,
		clerkId: "clerk_dark_chocolate_007",
		categoryId: "desserts",
	},
	{
		name: "raw whole almonds",
		slug: "raw-whole-almonds",
		description:
			"Crunchy raw almonds packed with protein and healthy fats. Perfect for snacking, baking, or blending into smoothies.",
		featured: false,
		image: "/products/pexels-1092730.jpeg",
		price: 740,
		specialPricePercent: 10,
		isNew: false,
		clerkId: "clerk_raw_almonds_008",
		categoryId: "snacks",
	},
	{
		name: "honey roasted cashews",
		slug: "honey-roasted-cashews",
		description:
			"Lightly roasted cashews coated with a touch of honey and sea salt. Sweet, buttery, and irresistibly crunchy.",
		featured: false,
		image: "/products/pexels-5632399.jpeg",
		price: 790,
		specialPricePercent: 12,
		isNew: false,
		clerkId: "clerk_cashews_009",
		categoryId: "snacks",
	},
	{
		name: "organic chia seeds",
		slug: "organic-chia-seeds",
		description:
			"Nutrient-dense chia seeds rich in fiber and omega-3s. Ideal for puddings, smoothies, and baking.",
		featured: false,
		image: "/products/pexels-4110256.jpeg",
		price: 460,
		specialPricePercent: 10,
		isNew: false,
		clerkId: "clerk_chia_seeds_010",
		categoryId: "salads",
	},
	{
		name: "flaxseed meal",
		slug: "flaxseed-meal",
		description:
			"Freshly milled flaxseed meal for easy digestion and maximum nutrition. Great for smoothies, oatmeal, or baking.",
		featured: false,
		image: "/products/pexels-4110255.jpeg",
		price: 380,
		specialPricePercent: 15,
		isNew: true,
		clerkId: "clerk_flax_meal_011",
		categoryId: "salads",
	},
	{
		name: "tri-color quinoa",
		slug: "tri-color-quinoa",
		description:
			"Fluffy tri-color quinoa with a nutty flavor and tender bite. Rinsed and ready for quick, wholesome meals.",
		featured: false,
		image: "/products/pexels-4110254.jpeg",
		price: 620,
		specialPricePercent: 12,
		isNew: false,
		clerkId: "clerk_quinoa_012",
		categoryId: "salads",
	},
	{
		name: "aged basmati rice",
		slug: "aged-basmati-rice",
		description:
			"Aromatic long-grain basmati rice aged for enhanced fragrance and fluffiness. Perfect for biryani, pilaf, and everyday meals.",
		featured: false,
		image: "/products/pexels-4110257.jpeg",
		price: 540,
		specialPricePercent: 10,
		isNew: false,
		clerkId: "clerk_basmati_rice_013",
		categoryId: "north-indian",
	},
	{
		name: "whole wheat pasta",
		slug: "whole-wheat-pasta",
		description:
			"Hearty whole wheat pasta with a firm bite and rich flavor. Made from stone-ground durum for a satisfying meal.",
		featured: false,
		image: "/products/pexels-1437267.jpeg",
		price: 360,
		specialPricePercent: 10,
		isNew: false,
		clerkId: "clerk_whole_wheat_pasta_014",
		categoryId: "italian",
	},
	{
		name: "san marzano tomatoes",
		slug: "san-marzano-tomatoes",
		description:
			"Whole peeled San Marzano tomatoes with a sweet, low-acid profile. Ideal for rich pasta sauces and slow-cooked dishes.",
		featured: false,
		image: "/products/pexels-2127027.jpeg",
		price: 280,
		specialPricePercent: 12,
		isNew: false,
		clerkId: "clerk_san_marzano_015",
		categoryId: "italian",
	},
	{
		name: "organic coconut milk",
		slug: "organic-coconut-milk",
		description:
			"Creamy organic coconut milk with no gums or additives. Perfect for curries, soups, and dairy-free desserts.",
		featured: false,
		image: "/products/pexels-5945844.jpeg",
		price: 320,
		specialPricePercent: 15,
		isNew: true,
		clerkId: "clerk_coconut_milk_016",
		categoryId: "north-indian",
	},
	{
		name: "pure maple syrup",
		slug: "pure-maple-syrup",
		description:
			"Grade A amber maple syrup with warm caramel notes. Harvested from sustainably managed maple groves.",
		featured: true,
		image: "/products/pexels-5945902.jpeg",
		price: 980,
		specialPricePercent: 10,
		isNew: false,
		clerkId: "clerk_maple_syrup_017",
		categoryId: "desserts",
	},
	{
		name: "strawberry preserves",
		slug: "strawberry-preserves",
		description:
			"Slow-cooked strawberry preserves with whole fruit pieces. Lightly sweet and perfect for toast or yogurt.",
		featured: false,
		image: "/products/pexels-5945899.jpeg",
		price: 410,
		specialPricePercent: 12,
		isNew: false,
		clerkId: "clerk_strawberry_jam_018",
		categoryId: "desserts",
	},
	{
		name: "creamy peanut butter",
		slug: "creamy-peanut-butter",
		description:
			"Smooth peanut butter made with roasted peanuts and a pinch of sea salt. No added sugars or oils.",
		featured: false,
		image: "/products/pexels-1092730.jpeg",
		price: 520,
		specialPricePercent: 10,
		isNew: false,
		clerkId: "clerk_peanut_butter_019",
		categoryId: "snacks",
	},
	{
		name: "almond butter",
		slug: "almond-butter",
		description:
			"Velvety almond butter with a rich roasted flavor. Great for spreading, baking, or blending into smoothies.",
		featured: false,
		image: "/products/pexels-5632399.jpeg",
		price: 690,
		specialPricePercent: 12,
		isNew: false,
		clerkId: "clerk_almond_butter_020",
		categoryId: "snacks",
	},
	{
		name: "greek yogurt",
		slug: "greek-yogurt",
		description:
			"Thick and creamy Greek yogurt with high protein and live cultures. Perfect for breakfast, dips, or smoothies.",
		featured: true,
		image: "/products/pexels-4040691.jpeg",
		price: 280,
		specialPricePercent: 15,
		isNew: true,
		clerkId: "clerk_greek_yogurt_021",
		categoryId: "salads",
	},
	{
		name: "aged cheddar cheese",
		slug: "aged-cheddar-cheese",
		description:
			"Sharp aged cheddar with a crumbly texture and deep nutty flavor. Aged for 12 months.",
		featured: false,
		image: "/products/pexels-5945901.jpeg",
		price: 560,
		specialPricePercent: 10,
		isNew: false,
		clerkId: "clerk_cheddar_022",
		categoryId: "snacks",
	},
	{
		name: "fresh mozzarella",
		slug: "fresh-mozzarella",
		description:
			"Soft, fresh mozzarella with a delicate milky flavor. Ideal for salads, pizza, and sandwiches.",
		featured: false,
		image: "/products/pexels-4110234.jpeg",
		price: 480,
		specialPricePercent: 12,
		isNew: false,
		clerkId: "clerk_mozzarella_023",
		categoryId: "italian",
	},
	{
		name: "free-range eggs",
		slug: "free-range-eggs",
		description:
			"Large free-range eggs with vibrant yolks. Raised on open pasture with natural feed.",
		featured: true,
		image: "/products/pexels-4040691.jpeg",
		price: 350,
		specialPricePercent: 10,
		isNew: false,
		clerkId: "clerk_free_range_eggs_024",
		categoryId: "north-indian",
	},
	{
		name: "grass-fed whole milk",
		slug: "grass-fed-whole-milk",
		description:
			"Creamy whole milk from grass-fed cows. Minimally processed with a naturally sweet taste.",
		featured: false,
		image: "/products/pexels-416656.jpeg",
		price: 260,
		specialPricePercent: 10,
		isNew: false,
		clerkId: "clerk_grass_fed_milk_025",
		categoryId: "beverages",
	},
	{
		name: "cultured butter",
		slug: "cultured-butter",
		description:
			"European-style cultured butter with a rich, tangy flavor. Made in small batches for exceptional quality.",
		featured: false,
		image: "/products/pexels-5945896.jpeg",
		price: 420,
		specialPricePercent: 15,
		isNew: true,
		clerkId: "clerk_cultured_butter_026",
		categoryId: "italian",
	},
	{
		name: "clarified ghee",
		slug: "clarified-ghee",
		description:
			"Clarified butter (ghee) with a nutty aroma and high smoke point. Perfect for sautéing and roasting.",
		featured: false,
		image: "/products/pexels-5945897.jpeg",
		price: 690,
		specialPricePercent: 12,
		isNew: false,
		clerkId: "clerk_ghee_027",
		categoryId: "north-indian",
	},
	{
		name: "crumbled feta",
		slug: "crumbled-feta",
		description:
			"Tangy crumbled feta cheese in brine. Great for salads, wraps, and Mediterranean dishes.",
		featured: false,
		image: "/products/pexels-5945895.jpeg",
		price: 430,
		specialPricePercent: 10,
		isNew: false,
		clerkId: "clerk_feta_028",
		categoryId: "salads",
	},
	{
		name: "organic firm tofu",
		slug: "organic-firm-tofu",
		description:
			"Protein-rich firm tofu made from organic soybeans. Ideal for stir-fries, grilling, or marinating.",
		featured: false,
		image: "/products/pexels-5945892.jpeg",
		price: 280,
		specialPricePercent: 10,
		isNew: false,
		clerkId: "clerk_tofu_029",
		categoryId: "north-indian",
	},
	{
		name: "organic tempeh",
		slug: "organic-tempeh",
		description:
			"Fermented tempeh with a nutty flavor and firm bite. Great for sandwiches, stir-fries, or salads.",
		featured: false,
		image: "/products/pexels-5945891.jpeg",
		price: 320,
		specialPricePercent: 12,
		isNew: false,
		clerkId: "clerk_tempeh_030",
		categoryId: "north-indian",
	},
	{
		name: "wild salmon fillet",
		slug: "wild-salmon-fillet",
		description:
			"Wild-caught salmon fillet with rich flavor and firm texture. Flash-frozen to preserve freshness.",
		featured: true,
		image: "/products/pexels-3296395.jpeg",
		price: 1890,
		specialPricePercent: 18,
		isNew: true,
		clerkId: "clerk_salmon_fillet_031",
		categoryId: "chinese",
	},
	{
		name: "jumbo shrimp",
		slug: "jumbo-shrimp",
		description:
			"Peeled and deveined jumbo shrimp, quick-frozen for peak freshness. Perfect for grilling or stir-fries.",
		featured: false,
		image: "/products/pexels-3296397.jpeg",
		price: 1580,
		specialPricePercent: 15,
		isNew: false,
		clerkId: "clerk_shrimp_032",
		categoryId: "chinese",
	},
	{
		name: "boneless chicken breast",
		slug: "boneless-chicken-breast",
		description:
			"Lean boneless chicken breast trimmed and ready to cook. Fresh, tender, and versatile for weeknight meals.",
		featured: true,
		image: "/products/pexels-616354.jpeg",
		price: 920,
		specialPricePercent: 12,
		isNew: false,
		clerkId: "clerk_chicken_breast_033",
		categoryId: "north-indian",
	},
	{
		name: "herb-marinated lamb chops",
		slug: "herb-marinated-lamb-chops",
		description:
			"Tender lamb chops marinated with rosemary, garlic, and olive oil. Quick-cooking and full of flavor.",
		featured: false,
		image: "/products/pexels-410648.jpeg",
		price: 2100,
		specialPricePercent: 20,
		isNew: false,
		clerkId: "clerk_lamb_chops_034",
		categoryId: "north-indian",
	},
	{
		name: "smoked pork sausage",
		slug: "smoked-pork-sausage",
		description:
			"Smoky pork sausage with a gentle spice blend. Great for breakfast or hearty pasta dishes.",
		featured: false,
		image: "/products/pexels-4106482.jpeg",
		price: 780,
		specialPricePercent: 12,
		isNew: false,
		clerkId: "clerk_pork_sausage_035",
		categoryId: "mexican",
	},
	{
		name: "crisp gala apples",
		slug: "crisp-gala-apples",
		description:
			"Sweet and crisp gala apples picked at peak ripeness. Perfect for snacking and baking.",
		featured: false,
		image: "/products/pexels-102104.jpeg",
		price: 320,
		specialPricePercent: 10,
		isNew: true,
		clerkId: "clerk_gala_apples_036",
		categoryId: "snacks",
	},
	{
		name: "ripe bananas",
		slug: "ripe-bananas",
		description:
			"Naturally sweet ripe bananas, great for smoothies, snacks, and baking.",
		featured: false,
		image: "/products/pexels-461208.jpeg",
		price: 180,
		specialPricePercent: 10,
		isNew: false,
		clerkId: "clerk_bananas_037",
		categoryId: "snacks",
	},
	{
		name: "fresh blueberries",
		slug: "fresh-blueberries",
		description:
			"Plump blueberries bursting with sweet-tart flavor. Ideal for oatmeal, baking, or snacking.",
		featured: true,
		image: "/products/pexels-894695.jpeg",
		price: 420,
		specialPricePercent: 12,
		isNew: false,
		clerkId: "clerk_blueberries_038",
		categoryId: "desserts",
	},
	{
		name: "strawberry punnet",
		slug: "strawberry-punnet",
		description:
			"Juicy strawberries with a bright, sweet aroma. Perfect for desserts or fresh snacking.",
		featured: true,
		image: "/products/pexels-934066.jpeg",
		price: 390,
		specialPricePercent: 12,
		isNew: false,
		clerkId: "clerk_strawberries_039",
		categoryId: "desserts",
	},
	{
		name: "hass avocados",
		slug: "hass-avocados",
		description:
			"Creamy hass avocados with buttery texture. Ideal for guacamole, salads, and toast.",
		featured: true,
		image: "/products/pexels-2228551.jpeg",
		price: 420,
		specialPricePercent: 10,
		isNew: false,
		clerkId: "clerk_avocados_040",
		categoryId: "salads",
	},
	{
		name: "lacinato kale",
		slug: "lacinato-kale",
		description:
			"Dark leafy lacinato kale with a tender texture. Great for salads, soups, and sautéing.",
		featured: false,
		image: "/products/pexels-5946073.jpeg",
		price: 260,
		specialPricePercent: 15,
		isNew: true,
		clerkId: "clerk_kale_041",
		categoryId: "salads",
	},
	{
		name: "baby spinach",
		slug: "baby-spinach",
		description:
			"Fresh baby spinach leaves washed and ready to use. Perfect for salads and quick sautés.",
		featured: false,
		image: "/products/pexels-5946076.jpeg",
		price: 240,
		specialPricePercent: 10,
		isNew: false,
		clerkId: "clerk_spinach_042",
		categoryId: "salads",
	},
	{
		name: "sweet carrots",
		slug: "sweet-carrots",
		description:
			"Crunchy sweet carrots freshly harvested. Ideal for snacking, roasting, and soups.",
		featured: false,
		image: "/products/pexels-65174.jpeg",
		price: 200,
		specialPricePercent: 10,
		isNew: false,
		clerkId: "clerk_carrots_043",
		categoryId: "salads",
	},
	{
		name: "baby potatoes",
		slug: "baby-potatoes",
		description:
			"Creamy baby potatoes with thin skins. Excellent for roasting and boiling.",
		featured: false,
		image: "/products/pexels-1092730.jpeg",
		price: 260,
		specialPricePercent: 10,
		isNew: false,
		clerkId: "clerk_baby_potatoes_044",
		categoryId: "north-indian",
	},
	{
		name: "red onions",
		slug: "red-onions",
		description:
			"Bold red onions with a crisp bite and mild sweetness. Great for salads and sautés.",
		featured: false,
		image: "/products/pexels-175692.jpeg",
		price: 180,
		specialPricePercent: 10,
		isNew: false,
		clerkId: "clerk_red_onions_045",
		categoryId: "salads",
	},
	{
		name: "mixed bell peppers",
		slug: "mixed-bell-peppers",
		description:
			"Colorful bell peppers with a sweet crunch. Perfect for stir-fries, salads, and roasting.",
		featured: false,
		image: "/products/pexels-5632399.jpeg",
		price: 320,
		specialPricePercent: 12,
		isNew: true,
		clerkId: "clerk_bell_peppers_046",
		categoryId: "salads",
	},
	{
		name: "english cucumbers",
		slug: "english-cucumbers",
		description:
			"Crisp English cucumbers with thin skins and mild flavor. Great for salads and sandwiches.",
		featured: false,
		image: "/products/pexels-2329440.jpeg",
		price: 220,
		specialPricePercent: 10,
		isNew: false,
		clerkId: "clerk_cucumbers_047",
		categoryId: "salads",
	},
	{
		name: "cherry tomatoes",
		slug: "cherry-tomatoes",
		description:
			"Juicy cherry tomatoes with a sweet burst. Perfect for salads, pasta, and snacking.",
		featured: false,
		image: "/products/pexels-533280.jpeg",
		price: 260,
		specialPricePercent: 10,
		isNew: false,
		clerkId: "clerk_cherry_tomatoes_048",
		categoryId: "salads",
	},
	{
		name: "aged balsamic vinegar",
		slug: "aged-balsamic-vinegar",
		description:
			"Slow-aged balsamic vinegar with a sweet, complex finish. Perfect for dressings and glazes.",
		featured: true,
		image: "/products/pexels-5945900.jpeg",
		price: 860,
		specialPricePercent: 15,
		isNew: false,
		clerkId: "clerk_balsamic_049",
		categoryId: "italian",
	},
	{
		name: "sea salt flakes",
		slug: "sea-salt-flakes",
		description:
			"Delicate sea salt flakes for finishing dishes. Adds a clean briny crunch to every bite.",
		featured: false,
		image: "/products/pexels-5945898.jpeg",
		price: 220,
		specialPricePercent: 10,
		isNew: false,
		clerkId: "clerk_sea_salt_050",
		categoryId: "salads",
	},
];
export default products;
